name: "🕷️ Bug report Bug报告"
description: "Report errors or unexpected behavior. 创建一个 Bug 报告以帮助我们改进。"
labels:
  - bug
body:
  - type: checkboxes
    attributes:
      label: "Please confirm before submission 在提交之前，请确认"
      options:
        - label: |
            I have searched for existing issues [search for existing issues](https://github.com/junjiem/dify-plugin-repackaging/issues), including closed ones. 
            我已经搜索了现有问题[搜索现有问题](https://github.com/junjiem/dify-plugin-repackaging/issues)，包括已关闭的问题。"
          required: true
  - type: dropdown
    attributes:
      label: OS Platform 操作系统平台
      description: Which OS Platform? 哪个操作系统平台？
      multiple: true
      options:
        - linux-amd64
        - linux-arm64
        - darwin-amd64
        - darwin-arm64
        - others
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Problem description 问题描述"
      description: "Please describe the problem you have encountered clearly and concisely. 请清晰简洁地描述你遇到的问题。"
    validations:
      required: true
